run:
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  revive:
    rules:
      - name: comment-spacings

issues:
  exclude-dirs:
    - test
  exclude-rules:
    - path: api/.*
      linters:
        - lll
    - path: internal/.*
      linters:
        - dupl
        - lll
