apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: helm
    contents:
    - path: image-distribution-operator
      directory:
        path: dist/chart/
      ignorePaths:
        - values.schema.json
        - values.yaml
        - Chart.yaml
        - templates/manager/manager.yaml
        - templates/network-policy/network-policy.yaml
