version: 2.1

orbs:
  architect: giantswarm/architect@5.11.4

jobs:
  tests:
    executor: architect/architect
    steps:
    - checkout
    - run:
        name: setup envtest
        command: CGO_ENABLED=0 make setup-envtest

workflows:
  test:
    jobs:
      - tests:
          filters:
            tags:
              only: /^v.*/
      - architect/go-build:
          context: architect
          name: go-build
          binary: template
          requires:
            - tests
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main
                - master
      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: package-and-push-chart
          app_catalog: giantswarm-playground-catalog
          app_catalog_test: giantswarm-playground-test-catalog
          chart: image-distribution-operator
            # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
              - main
              - master
      