version: 2.1

orbs:
  architect: giantswarm/architect@5.11.4

workflows:
  test:
    jobs:
      - architect/go-build:
          context: architect
          name: go-build
          binary: template
          path: ./cmd
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main
                - master
      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: push-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "image-distribution-operator"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          context: architect
          name: push-to-vsphere-app-collection
          app_name: "image-distribution-operator"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
