---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - image.giantswarm.io
  resources:
  - nodeimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.giantswarm.io
  resources:
  - nodeimages/finalizers
  verbs:
  - update
- apiGroups:
  - image.giantswarm.io
  resources:
  - nodeimages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - release.giantswarm.io.giantswarm.io
  resources:
  - releases
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - release.giantswarm.io.giantswarm.io
  resources:
  - releases/finalizers
  verbs:
  - update
- apiGroups:
  - release.giantswarm.io.giantswarm.io
  resources:
  - releases/status
  verbs:
  - get
  - patch
  - update
