apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: image-distribution-operator-vsphere-credentials
  namespace: {{ .Release.Namespace }}
data:
  credentials.yaml: |-
    {{- .Values.vsphere.credentials | toYaml | nindent 4 }}
type: Opaque
