apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: image-distribution-operator-vsphere-locations
  namespace: {{ .Release.Namespace }}
data:
  locations: |-
    {{- .Values.vsphere.locations | toYaml | nindent 4 }}
